CREATE TABLE games (
    game_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    player     VARCHAR2(64) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_games PRIMARY KEY (game_id)
);

CREATE TABLE moves (
    move_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    game_id       NUMBER NOT NULL,
    turn_no       NUMBER(3) NOT NULL,
    player        CHAR(1) NOT NULL,
    column_number NUMBER(1) NOT NULL,
    CONSTRAINT pk_moves PRIMARY KEY (move_id),
    CONSTRAINT fk_moves_games FOREIGN KEY (game_id) REFERENCES games (game_id) ON DELETE CASCADE,
    CONSTRAINT uq_moves_turn UNIQUE (game_id, turn_no),
    CONSTRAINT ck_moves_player CHECK (player IN ('X', 'O')),
    CONSTRAINT ck_moves_column CHECK (column_number BETWEEN 1 AND 7)
);

CREATE INDEX ix_moves_game_column ON moves (game_id, column_number, turn_no);

CREATE OR REPLACE VIEW cells AS
    SELECT
        game_id,
        column_number AS x,
        player,
        ROW_NUMBER() OVER (PARTITION BY game_id, column_number ORDER BY turn_no) AS y
    FROM moves;
