// Regenerate the showcase data with whichever Python is installed, so the exact
// command never has to be remembered by hand: `npm start`, `npm run build` and
// `npm run data` all end up running the repository's own generator, which stays
// the single source of truth for what the dashboard shows.
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const GENERATOR = fileURLToPath(new URL("generate_dashboard.py", import.meta.url));

// `python` first on Windows (where it is the launcher most installs provide) and
// `python3` first elsewhere, with the other as a fallback either way.
const INTERPRETERS = process.platform === "win32"
    ? ["python", "python3", "py"]
    : ["python3", "python"];

function findPython() {
    for (const interpreter of INTERPRETERS) {
        const probe = spawnSync(interpreter, ["--version"], { stdio: "ignore" });
        if (!probe.error && probe.status === 0) {
            return interpreter;
        }
    }
    return null;
}

const interpreter = findPython();
if (!interpreter) {
    console.error(
        "error: no Python interpreter found on PATH (tried " + INTERPRETERS.join(", ") + ").\n" +
        "The showcase data is generated by " + GENERATOR + ", which needs Python 3.8+.",
    );
    process.exit(1);
}

// stdio: "inherit" keeps the generator's own progress and warnings visible, and its
// exit status becomes this script's, so `npm start` stops on a broken generator.
const run = spawnSync(interpreter, [GENERATOR], { stdio: "inherit" });
process.exit(run.status ?? 1);
